//
//  ZagakuDemoKit.swift
//  ZagakuDemo
//
//  Created by Eric Meyer on 3/28/18.
//  Copyright © 2018 (null). All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class ZagakuDemoKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawBasicShape(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 300), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 300, height: 300), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 300, y: resizedFrame.height / 300)


        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 150, y: 0))
        starPath.addLine(to: CGPoint(x: 202.9, y: 77.19))
        starPath.addLine(to: CGPoint(x: 292.66, y: 103.65))
        starPath.addLine(to: CGPoint(x: 235.6, y: 177.81))
        starPath.addLine(to: CGPoint(x: 238.17, y: 271.35))
        starPath.addLine(to: CGPoint(x: 150, y: 240))
        starPath.addLine(to: CGPoint(x: 61.83, y: 271.35))
        starPath.addLine(to: CGPoint(x: 64.4, y: 177.81))
        starPath.addLine(to: CGPoint(x: 7.34, y: 103.65))
        starPath.addLine(to: CGPoint(x: 97.1, y: 77.19))
        starPath.close()
        UIColor.gray.setFill()
        starPath.fill()
        
        context.restoreGState()

    }




    @objc(ZagakuDemoKitResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
